// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccountStatus() {
  return window['go']['main']['App']['AccountStatus']();
}

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function Analyze(arg1) {
  return window['go']['main']['App']['Analyze'](arg1);
}

export function AttachFiles(arg1) {
  return window['go']['main']['App']['AttachFiles'](arg1);
}

export function AttachTextPaths(arg1) {
  return window['go']['main']['App']['AttachTextPaths'](arg1);
}

export function BeginCodexLogin() {
  return window['go']['main']['App']['BeginCodexLogin']();
}

export function BuildUsageReport(arg1, arg2) {
  return window['go']['main']['App']['BuildUsageReport'](arg1, arg2);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function Command(arg1) {
  return window['go']['main']['App']['Command'](arg1);
}

export function CompactConversation(arg1) {
  return window['go']['main']['App']['CompactConversation'](arg1);
}

export function CompletePath(arg1, arg2) {
  return window['go']['main']['App']['CompletePath'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreatePlan(arg1) {
  return window['go']['main']['App']['CreatePlan'](arg1);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function DeletePlan(arg1) {
  return window['go']['main']['App']['DeletePlan'](arg1);
}

export function DiscoverMCPTools(arg1) {
  return window['go']['main']['App']['DiscoverMCPTools'](arg1);
}

export function ExecutePlan(arg1) {
  return window['go']['main']['App']['ExecutePlan'](arg1);
}

export function InstallMarketPackage(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallMarketPackage'](arg1, arg2, arg3);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function LoadSession(arg1, arg2) {
  return window['go']['main']['App']['LoadSession'](arg1, arg2);
}

export function MCPState() {
  return window['go']['main']['App']['MCPState']();
}

export function Marketplace(arg1) {
  return window['go']['main']['App']['Marketplace'](arg1);
}

export function Models() {
  return window['go']['main']['App']['Models']();
}

export function OpenCodexLogin() {
  return window['go']['main']['App']['OpenCodexLogin']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Plans() {
  return window['go']['main']['App']['Plans']();
}

export function PollCodexLogin(arg1) {
  return window['go']['main']['App']['PollCodexLogin'](arg1);
}

export function PreviewFile(arg1) {
  return window['go']['main']['App']['PreviewFile'](arg1);
}

export function PromptDefaults() {
  return window['go']['main']['App']['PromptDefaults']();
}

export function ReadPlan(arg1) {
  return window['go']['main']['App']['ReadPlan'](arg1);
}

export function ReadSession(arg1, arg2) {
  return window['go']['main']['App']['ReadSession'](arg1, arg2);
}

export function ReadSkill(arg1) {
  return window['go']['main']['App']['ReadSkill'](arg1);
}

export function RenamePath(arg1) {
  return window['go']['main']['App']['RenamePath'](arg1);
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function SaveAccountKeys(arg1) {
  return window['go']['main']['App']['SaveAccountKeys'](arg1);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SaveCurrentSession(arg1) {
  return window['go']['main']['App']['SaveCurrentSession'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SavePlan(arg1, arg2) {
  return window['go']['main']['App']['SavePlan'](arg1, arg2);
}

export function SavePrompts(arg1) {
  return window['go']['main']['App']['SavePrompts'](arg1);
}

export function SaveSkill(arg1) {
  return window['go']['main']['App']['SaveSkill'](arg1);
}

export function SaveUsageReport(arg1) {
  return window['go']['main']['App']['SaveUsageReport'](arg1);
}

export function SearchSessions(arg1) {
  return window['go']['main']['App']['SearchSessions'](arg1);
}

export function SendAlso(arg1) {
  return window['go']['main']['App']['SendAlso'](arg1);
}

export function Sessions(arg1) {
  return window['go']['main']['App']['Sessions'](arg1);
}

export function SetBotName(arg1) {
  return window['go']['main']['App']['SetBotName'](arg1);
}

export function SetModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetModel'](arg1, arg2, arg3);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetWorkingDirectory(arg1) {
  return window['go']['main']['App']['SetWorkingDirectory'](arg1);
}

export function Skills() {
  return window['go']['main']['App']['Skills']();
}

export function State() {
  return window['go']['main']['App']['State']();
}

export function Submit(arg1) {
  return window['go']['main']['App']['Submit'](arg1);
}

export function Tasks() {
  return window['go']['main']['App']['Tasks']();
}

export function Thoughts() {
  return window['go']['main']['App']['Thoughts']();
}

export function ToggleMCPServer(arg1, arg2) {
  return window['go']['main']['App']['ToggleMCPServer'](arg1, arg2);
}

export function Usage() {
  return window['go']['main']['App']['Usage']();
}
