// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {app} from '../models';

export function AccountStatus():Promise<main.AccountState>;

export function AddMCPServer(arg1:main.MCPInput):Promise<main.UIState>;

export function Analyze(arg1:string):Promise<app.Reply>;

export function AttachFiles(arg1:Array<string>):Promise<Array<main.AttachmentInfo>>;

export function AttachTextPaths(arg1:string):Promise<Array<main.AttachmentInfo>>;

export function BeginCodexLogin():Promise<app.CodexDeviceFlow>;

export function BuildUsageReport(arg1:main.UsageFilter,arg2:boolean):Promise<main.UsageReport>;

export function CancelScheduledTask(arg1:string):Promise<Array<app.ScheduledTask>>;

export function CancelTask(arg1:string):Promise<Array<app.AgentTask>>;

export function Command(arg1:string):Promise<app.Reply>;

export function CompactConversation(arg1:string):Promise<app.Reply>;

export function CompletePath(arg1:string,arg2:string):Promise<Array<main.PathSuggestion>>;

export function CreateDirectory(arg1:main.FileCreateRequest):Promise<main.FileBrowser>;

export function CreateFile(arg1:main.FileCreateRequest):Promise<main.FileBrowser>;

export function CreatePlan(arg1:string):Promise<app.Reply>;

export function CreateScheduledTask(arg1:app.ScheduleRequest):Promise<Array<app.ScheduledTask>>;

export function DeletePath(arg1:string):Promise<main.FileBrowser>;

export function DeletePlan(arg1:string):Promise<app.Reply>;

export function DeleteScheduledTask(arg1:string):Promise<Array<app.ScheduledTask>>;

export function DiscoverMCPTools(arg1:string):Promise<Array<main.MCPToolInfo>>;

export function ExecutePlan(arg1:string):Promise<app.Reply>;

export function InstallMarketPackage(arg1:string,arg2:boolean,arg3:boolean):Promise<main.MarketState>;

export function ListFiles(arg1:string):Promise<main.FileBrowser>;

export function LoadSession(arg1:string,arg2:number):Promise<app.Reply>;

export function MCPState():Promise<Record<string, any>>;

export function Marketplace(arg1:boolean):Promise<main.MarketState>;

export function Models():Promise<Array<app.ModelGroup>>;

export function OpenCodexLogin():Promise<main.AccountState>;

export function Pause():Promise<app.Reply>;

export function Plans():Promise<app.Reply>;

export function PollCodexLogin(arg1:app.CodexDeviceFlow):Promise<main.CodexLoginPollState>;

export function PreviewFile(arg1:string):Promise<main.FilePreview>;

export function PromptDefaults():Promise<main.PromptDefaults>;

export function ReadPlan(arg1:string):Promise<app.Plan>;

export function ReadSession(arg1:string,arg2:number):Promise<Array<app.Message>>;

export function ReadSkill(arg1:string):Promise<main.FilePreview>;

export function RenamePath(arg1:main.FileRenameRequest):Promise<main.FileBrowser>;

export function Resume():Promise<app.Reply>;

export function RunScheduledTaskNow(arg1:string):Promise<Array<app.ScheduledTask>>;

export function SaveAccountKeys(arg1:app.APIKeys):Promise<main.AccountState>;

export function SaveConfig(arg1:app.Config,arg2:app.APIKeys):Promise<main.UIState>;

export function SaveCurrentSession(arg1:string):Promise<main.SessionSummary>;

export function SaveFile(arg1:main.SaveFileRequest):Promise<main.FilePreview>;

export function SavePlan(arg1:string,arg2:string):Promise<app.Reply>;

export function SavePrompts(arg1:app.PromptConfig):Promise<main.UIState>;

export function SaveSkill(arg1:main.SkillSaveRequest):Promise<main.SkillFile>;

export function SaveUsageReport(arg1:main.UsageFilter):Promise<main.UsageReport>;

export function ScheduledTasks():Promise<Array<app.ScheduledTask>>;

export function SearchSessions(arg1:string):Promise<Array<main.SessionSummary>>;

export function SendAlso(arg1:string):Promise<app.Reply>;

export function Sessions(arg1:number):Promise<Array<main.SessionSummary>>;

export function SetBotName(arg1:string):Promise<main.UIState>;

export function SetModel(arg1:string,arg2:string,arg3:string):Promise<main.UIState>;

export function SetTheme(arg1:string):Promise<main.UIState>;

export function SetWorkingDirectory(arg1:string):Promise<main.FileBrowser>;

export function Skills():Promise<Array<main.SkillFile>>;

export function State():Promise<main.UIState>;

export function Submit(arg1:string):Promise<app.Reply>;

export function Tasks():Promise<Array<app.AgentTask>>;

export function Thoughts():Promise<Array<app.ThoughtSnapshot>>;

export function ToggleMCPServer(arg1:string,arg2:string):Promise<main.UIState>;

export function Usage():Promise<app.UsageSnapshot>;
